apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-formation
  labels:
    type: local
spec:
  storageClassName: formation
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/formation"
    type: DirectoryOrCreate