apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-deploy
  labels:
    app: multi-deploy
    projet: formation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-deploy
  template:
    metadata:
      labels:
        app: multi-deploy
    spec:
      containers:
        - name: nginx
          image: nginx:1.18-alpine
          volumeMounts:
            - name: partage-multipod
              mountPath: /usr/share/nginx/html
      initContainers:
        - name: debian
          image: debian:buster-slim
          command: ["/bin/bash"]
          args: ["-c", "echo Message depuis debian satellite > /partage/index.html"]
          volumeMounts:
            - name: partage-multipod
              mountPath: /partage
      volumes:
        - name: partage-multipod
          emptyDir: {}