apiVersion: v1
kind: Pod
metadata:
  name: multipod
spec:
  containers:
    - image: nginx:1.18-alpine
      name: nginx
    - image: debian:buster-slim
      name: debian
      command: ["sleep", "300"]