apiVersion: v1
kind: Pod
metadata:
  name: multipod
spec:
  containers:
    - name: nginx
      image: nginx:1.18-alpine
      volumeMounts:
        - name: partage-multipod
          mountPath: /usr/share/nginx/html
    - name: debian
      image: debian:buster-slim
      command: ["/bin/bash"]
      args: ["-c", "echo Message depuis debian satellite > /partage/index.html"]
      volumeMounts:
        - name: partage-multipod
          mountPath: /partage
  volumes:
    - name: partage-multipod
      emptyDir: {}