apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    k8s-app: watch
  name: pod-watch
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-watch
subjects:
  - kind: ServiceAccount
    name: formation
    namespace: default