kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    k8s-app: watch
  name: pod-watch
  namespace: default
rules:
  # Allow Dashboard to get, update and delete Dashboard exclusive secrets.
  - resources: [ deployment ]
    apiGroups: [ apps ]
    verbs: [ get, list ]