apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mongodb
  name: mongodb
  namespace: mongodb
spec:
  nodeSelector:
    type: database
  containers:
  - image: mongo:4.4
    name: mongodb
    volumeMounts:
      - mountPath: /data/db
        name: mongodb-volume
  restartPolicy: Always
  volumes:
  - name: mongodb-volume
    hostPath:
      # chemin du dossier sur l'hôte
      path: /node-mongodb
      # ce champ est optionnel
      type: DirectoryOrCreate

