apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  labels:
    app: myphp-frontend
    projet: myphp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myphp-frontend
  template:
    metadata:
      labels:
        app: myphp-frontend
    spec:
      containers:
      - name: backend
        image: bilbloke/frontend:1.0
        ports:
        - containerPort: 80