apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
  labels:
    app: nginx
    projet: npm
data:
  config: |
    server {
      index index.php index.html;
      error_log  /var/log/nginx/error.log;
      access_log /var/log/nginx/access.log;
      location / {
          try_files $uri $uri/ /index.php?$query_string;
      }

      location ~* \.php$ {
        fastcgi_index   index.php;
        fastcgi_pass    php-service:9000;
        include         fastcgi_params;
        fastcgi_param   SCRIPT_FILENAME    /srv/http$fastcgi_script_name;
        fastcgi_param   SCRIPT_NAME        $fastcgi_script_name;
      }
    }

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-npm
  labels:
    app: nginx
    projet: npm
spec:
  volumes:
  - name: config
    configMap:
      name: nginx-cm
      items:
      - key: config
        path: site.conf
  containers:
  - name: nginx
    image: nginx:1.18
    ports:
      - containerPort: 80
    volumeMounts:
    - name: config
      mountPath: /etc/nginx/conf.d


---

apiVersion: v1
kind: Pod
metadata:
  name: php
  labels:
    app: php
    projet: npm
spec:
  volumes:
  - name: php-volume
    emptyDir: {}
  initContainers:
  - name: side-car
    image: busybox
    volumeMounts:
    - name: php-volume
      mountPath: /php_code
    command:
    - wget
    - "-O"
    - "/php_code/index.php"
    - https://raw.githubusercontent.com/psable/php/main/myphp.php
  containers:
  - name: php
    image: phpdockerio/php73-fpm
    volumeMounts:
    - name: php-volume
      mountPath: /srv/http

---

apiVersion: v1
kind: Service
metadata:
  name: php-service
  labels:
    projet: npm
    app: php
spec:
  type: ClusterIP
  selector:
    app: php
    projet: npm
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000


---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
    projet: npm
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31222
